# -*- coding: utf-8 -*-
"""
/***************************************************************************
 multicollinearity_test
                                 A QGIS plugin
 This plugin can calculate the Pearson correlation coefficient (r) to identify variables that exhibit multicollinearity 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-05
        copyright            : (C) 2026 by Muhammad Parif
        email                : payip28muhammad@apps.ipb.ac.id
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load multicollinearity_test class from file multicollinearity_test.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .multicollinearity_test import multicollinearity_test
    return multicollinearity_test(iface)
